### ISSUE TITLE
Matching Engine

### ISSUE THREAD

**Issue by iZMC** [glias/deal-maker-cli#12]

**Comment by iZMC** [comment]
## TODO

- [ ] 1. match end condition  refactor
- [ ] 2. const (PRIVATE_KEY_PATH..) adjust
- [ ] 3. after match change order status
- [ ] 4.  input cell order
